name: Build y Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar código
      - name: Descargar código
        uses: actions/checkout@v4

      # 2. Login en GitHub Container Registry
      - name: Login en GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # 3. Construir imagen Docker
      - name: Construir imagen
        run: |
          docker build -t ghcr.io/victor1997h/semana8:latest .

      # 4. Subir imagen a GHCR
      - name: Publicar imagen
        run: |
          docker push ghcr.io/victor1997h/semana8:latest